[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
maud = { version = "*", features = ["rocket"] }
rocket = { version = "0.5.1", features = ["json", "serde_json"] }
serde = "1.0.207"